import React, { createContext, useState, useEffect, ReactNode, useCallback } from 'react';
import { doc, onSnapshot, setDoc, updateDoc, collection } from 'firebase/firestore';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged, User as FirebaseUser } from 'firebase/auth';
import { db, auth } from '../firebase/config';
import { AppState, User, UserRole, ItemType, ResultStatus, Result, TabulationEntry, ScheduledEvent, Team, Grade, Judge, CodeLetter, Participant, JudgeAssignment, Category, Item, PerformanceType } from '../types';
import { DEFAULT_PAGE_PERMISSIONS, TABS } from '../constants';

// --- Default State Template ---
const defaultState: AppState = {
  settings: {
    organizingTeam: 'Knowledge Fest Committee',
    heading: 'Knowledge Fest 2024',
    description: 'A platform for showcasing talent and intelligence.',
    eventDates: [],
    maxItemsPerParticipant: { onStage: 5, offStage: 5 },
    maxTotalItemsPerParticipant: null,
    defaultParticipantsPerItem: 10,
    instructions: {},
    generalInstructions: 'Welcome to the festival! All participants are requested to adhere to the schedule and rules.',
    rankingStrategy: 'highest_mark',
    autoCodeAssignment: false,
    enableFloatingNav: false,
    mobileSidebarMode: 'floating',
    lotEligibleCodes: [],
    eventDays: [],
    stages: [],
    timeSlots: [],
    defaultPoints: {
      single: { first: 5, second: 3, third: 1 },
      group: { first: 10, second: 7, third: 5 },
    },
    reportSettings: {
      heading: 'Knowledge Fest Report',
      description: 'Official Report Document',
      header: 'Knowledge Fest Manager',
      footer: 'Generated by Knowledge Fest Manager',
    },
    institutionDetails: { name: '', address: '', email: '', contactNumber: '', description: '', logoUrl: '' },
    branding: { typographyUrl: '', teamLogoUrl: '' },
    customFonts: {},
    generalCustomFonts: [], 
    customTemplates: [], 
    customFooters: [], 
    customBackgrounds: [], 
  },
  categories: [],
  teams: [],
  items: [],
  gradePoints: { single: [], group: [] },
  codeLetters: [],
  participants: [],
  schedule: [],
  judgeAssignments: [],
  tabulation: [],
  results: [],
  judges: [],
  users: [
    { id: 'user_admin_01', username: 'admin', role: UserRole.MANAGER },
    { id: 'user_amazio_01', username: 'Amazio', role: UserRole.MANAGER }
  ],
  permissions: DEFAULT_PAGE_PERMISSIONS,
};

const cleanData = (data: any): any => {
    if (Array.isArray(data)) return data.map(cleanData);
    if (data !== null && typeof data === 'object') {
        return Object.fromEntries(
            Object.entries(data)
                .filter(([_, value]) => value !== undefined)
                .map(([key, value]) => [key, cleanData(value)])
        );
    }
    return data;
};

interface FirebaseContextType {
  state: AppState | null;
  currentUser: User | null;
  firebaseUser: FirebaseUser | null; 
  loading: boolean;
  isOnline: boolean;
  globalFilters: { teamId: string[]; categoryId: string[]; performanceType: string[]; itemId: string[]; status: ResultStatus[]; date: string[]; stage: string[]; };
  setGlobalFilters: React.Dispatch<React.SetStateAction<{ teamId: string[]; categoryId: string[]; performanceType: string[]; itemId: string[]; status: ResultStatus[]; date: string[]; stage: string[]; }>>;
  globalSearchTerm: string;
  setGlobalSearchTerm: React.Dispatch<React.SetStateAction<string>>;
  dataEntryView: 'ITEMS' | 'PARTICIPANTS';
  setDataEntryView: (view: 'ITEMS' | 'PARTICIPANTS') => void;
  itemsSubView: 'ITEMS' | 'PARTICIPANTS';
  setItemsSubView: (v: 'ITEMS' | 'PARTICIPANTS') => void;
  gradeSubView: 'CODES' | 'GRADES';
  setGradeSubView: (v: 'CODES' | 'GRADES') => void;
  scoringSubView: 'QUEUE' | 'LEDGER';
  setScoringSubView: (v: 'QUEUE' | 'LEDGER') => void;
  judgesSubView: 'ASSIGNMENTS' | 'REGISTRY' | 'OVERVIEW';
  setJudgesSubView: (v: 'ASSIGNMENTS' | 'REGISTRY' | 'OVERVIEW') => void;
  settingsSubView: string;
  setSettingsSubView: (v: string) => void;
  login: (username: string, pass: string, rememberMe: boolean) => Promise<void>;
  logout: () => Promise<void>;
  updateSettings: (payload: Partial<AppState['settings']>) => Promise<void>;
  addCategory: (payload: Omit<Category, 'id'>) => Promise<void>;
  addMultipleCategories: (payload: Category[]) => Promise<void>;
  updateCategory: (payload: Category) => Promise<void>;
  reorderCategories: (payload: Category[]) => Promise<void>;
  deleteMultipleCategories: (ids: string[]) => Promise<void>;
  addTeam: (payload: Omit<Team, 'id'>) => Promise<void>;
  addMultipleTeams: (payload: Team[]) => Promise<void>;
  updateTeam: (payload: Team) => Promise<void>;
  reorderTeams: (payload: Team[]) => Promise<void>;
  deleteMultipleTeams: (ids: string[]) => Promise<void>;
  addItem: (payload: Omit<Item, 'id'>) => Promise<void>;
  addMultipleItems: (payload: Item[]) => Promise<void>;
  updateItem: (payload: Item) => Promise<void>;
  deleteMultipleItems: (ids: string[]) => Promise<void>;
  addGrade: (payload: { itemType: 'single' | 'group', grade: Omit<Grade, 'id'> }) => Promise<void>;
  updateGrade: (payload: { itemType: 'single' | 'group', grade: Grade }) => Promise<void>;
  deleteGrade: (payload: { itemType: 'single' | 'group', gradeId: string }) => Promise<void>;
  addCodeLetter: (payload: Omit<CodeLetter, 'id'>) => Promise<void>;
  addMultipleCodeLetters: (payloads: CodeLetter[]) => Promise<void>;
  updateCodeLetter: (payload: CodeLetter) => Promise<void>;
  reorderCodeLetters: (payload: CodeLetter[]) => Promise<void>;
  deleteCodeLetter: (id: string) => Promise<void>;
  addJudge: (payload: { name: string; place?: string; profession?: string; }) => Promise<void>;
  updateJudge: (payload: Judge) => Promise<void>;
  reorderJudges: (payload: Judge[]) => Promise<void>;
  deleteMultipleJudges: (ids: string[]) => Promise<void>;
  updateItemJudges: (payload: { itemId: string, categoryId: string, judgeIds: string[] }) => Promise<void>;
  setJudgeAssignments: (payload: JudgeAssignment[]) => Promise<void>;
  addParticipant: (payload: Omit<Participant, 'id'>) => Promise<void>;
  addMultipleParticipants: (payload: Participant[]) => Promise<void>;
  updateParticipant: (payload: Participant) => Promise<void>;
  updateMultipleParticipants: (payload: Participant[]) => Promise<void>;
  deleteMultipleParticipants: (ids: string[]) => Promise<void>;
  setSchedule: (payload: ScheduledEvent[]) => Promise<void>;
  addScheduleEvent: (payload: ScheduledEvent) => Promise<void>; 
  updateTabulationEntry: (payload: TabulationEntry) => Promise<void>;
  updateMultipleTabulationEntries: (payload: TabulationEntry[]) => Promise<void>;
  deleteEventTabulation: (itemId: string) => Promise<void>;
  saveResult: (payload: Result) => Promise<void>;
  addUser: (payload: Omit<User, 'id'>) => Promise<void>;
  updateUser: (payload: User) => Promise<void>;
  deleteUser: (id: string) => Promise<void>;
  updatePermissions: (payload: { role: UserRole, pages: string[] }) => Promise<void>;
  updateInstruction: (payload: { page: string, text: string }) => Promise<void>;
  hasPermission: (tab: string) => boolean;
  backupData: () => void;
  restoreData: (file: File) => Promise<void>;
}

export const FirebaseContext = createContext<FirebaseContextType | null>(null);

const BASE_COLLECTION = 'artfest_v2';

export const FirebaseProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [state, setState] = useState<AppState | null>(null);
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [firebaseUser, setFirebaseUser] = useState<FirebaseUser | null>(null);
  const [loadingMap, setLoadingMap] = useState<Record<string, boolean>>({});
  const [authLoading, setAuthLoading] = useState(true);
  const [isOnline, setIsOnline] = useState(navigator.onLine);
  const [error, setError] = useState<string | null>(null);
  
  const [globalFilters, setGlobalFilters] = useState({ teamId: [] as string[], categoryId: [] as string[], performanceType: [] as string[], itemId: [] as string[], status: [] as ResultStatus[], date: [] as string[], stage: [] as string[] });
  const [globalSearchTerm, setGlobalSearchTerm] = useState('');
  
  const [dataEntryView, setDataEntryView] = useState<'ITEMS' | 'PARTICIPANTS'>('ITEMS');
  const [itemsSubView, setItemsSubView] = useState<'ITEMS' | 'PARTICIPANTS'>('ITEMS');
  const [gradeSubView, setGradeSubView] = useState<'CODES' | 'GRADES'>('CODES');
  const [scoringSubView, setScoringSubView] = useState<'QUEUE' | 'LEDGER'>('QUEUE');
  const [judgesSubView, setJudgesSubView] = useState<'ASSIGNMENTS' | 'REGISTRY' | 'OVERVIEW'>('ASSIGNMENTS');
  const [settingsSubView, setSettingsSubView] = useState('details');

  useEffect(() => {
    const handleStatusChange = () => setIsOnline(navigator.onLine);
    window.addEventListener('online', handleStatusChange);
    window.addEventListener('offline', handleStatusChange);
    return () => {
        window.removeEventListener('online', handleStatusChange);
        window.removeEventListener('offline', handleStatusChange);
    };
  }, []);

  useEffect(() => {
    const unsubscribeAuth = onAuthStateChanged(auth, (user) => {
        setFirebaseUser(user);
        setAuthLoading(false); 
    });
    return () => unsubscribeAuth();
  }, []);

  // Set up individual listeners for each data block
  useEffect(() => {
    const dataKeys = Object.keys(defaultState);
    const initialLoading: Record<string, boolean> = {};
    dataKeys.forEach(k => initialLoading[k] = true);
    setLoadingMap(initialLoading);

    const unsubscribers = dataKeys.map(key => {
      return onSnapshot(doc(db, BASE_COLLECTION, key), (snapshot) => {
        const data = snapshot.data();
        setState(prev => {
          const current = prev || defaultState;
          return { ...current, [key]: data ? data.value : defaultState[key as keyof AppState] };
        });
        setLoadingMap(prev => ({ ...prev, [key]: false }));
      }, (e) => {
        console.warn(`Listener failed for ${key}, falling back to default values. Error: ${e.message}`);
        setState(prev => {
          const current = prev || defaultState;
          return { ...current, [key]: (defaultState as any)[key] };
        });
        setLoadingMap(prev => ({ ...prev, [key]: false }));
      });
    });

    return () => unsubscribers.forEach(unsub => unsub());
  }, []);

  useEffect(() => {
    if (state && firebaseUser) {
        const email = firebaseUser.email || '';
        const username = email.split('@')[0].trim().toLowerCase();
        const appUser = state.users.find(u => u.username.toLowerCase() === username);
        if (appUser) setCurrentUser(appUser);
    } else {
        setCurrentUser(null);
    }
  }, [state, firebaseUser]);

  const login = async (username: string, pass: string) => {
    const email = `${username}@artfest.com`;
    await signInWithEmailAndPassword(auth, email, pass);
  };

  const logout = async () => {
    await signOut(auth);
    setCurrentUser(null);
    setFirebaseUser(null);
  };

  const writeDoc = async (key: string, value: any) => {
    const docRef = doc(db, BASE_COLLECTION, key);
    const sanitizedValue = cleanData(value);
    await setDoc(docRef, { value: sanitizedValue }, { merge: false });
  };

  const genericOps = (listName: keyof AppState) => ({
      add: async (payload: any) => {
          if (!state) return;
          const newList = [...(state[listName] as any[]), { ...payload, id: `${listName}_${Date.now()}` }];
          await writeDoc(listName, newList);
      },
      update: async (payload: any) => {
          if (!state) return;
          const newList = (state[listName] as any[]).map(item => item.id === payload.id ? payload : item);
          await writeDoc(listName, newList);
      },
      deleteMultiple: async (ids: string[]) => {
          if (!state) return;
          const newList = (state[listName] as any[]).filter(item => !ids.includes(item.id));
          await writeDoc(listName, newList);
      }
  });

  const catOps = genericOps('categories');
  const teamOps = genericOps('teams');
  const itemOps = genericOps('items');
  const partOps = genericOps('participants');

  const isLoading = authLoading || Object.values(loadingMap).some(v => v);

  const contextValue: FirebaseContextType = {
    state, currentUser, firebaseUser, loading: isLoading, isOnline,
    login, logout, globalFilters, setGlobalFilters, globalSearchTerm, setGlobalSearchTerm,
    dataEntryView, setDataEntryView, itemsSubView, setItemsSubView, gradeSubView, setGradeSubView,
    scoringSubView, setScoringSubView, judgesSubView, setJudgesSubView, settingsSubView, setSettingsSubView,
    updateSettings: (p) => writeDoc('settings', { ...state?.settings, ...p }),
    addCategory: catOps.add, addMultipleCategories: async (p) => writeDoc('categories', [...(state?.categories || []), ...p]),
    updateCategory: catOps.update, reorderCategories: (p) => writeDoc('categories', p), deleteMultipleCategories: catOps.deleteMultiple,
    addTeam: teamOps.add, addMultipleTeams: async (p) => writeDoc('teams', [...(state?.teams || []), ...p]),
    updateTeam: teamOps.update, reorderTeams: (p) => writeDoc('teams', p), deleteMultipleTeams: teamOps.deleteMultiple,
    addItem: itemOps.add, addMultipleItems: async (p) => writeDoc('items', [...(state?.items || []), ...p]),
    updateItem: itemOps.update, deleteMultipleItems: itemOps.deleteMultiple,
    addGrade: async ({ itemType, grade }) => {
        const list = [...state!.gradePoints[itemType], { ...grade, id: `g_${Date.now()}` }];
        await writeDoc('gradePoints', { ...state!.gradePoints, [itemType]: list });
    },
    updateGrade: async ({ itemType, grade }) => {
        const list = state!.gradePoints[itemType].map(g => g.id === grade.id ? grade : g);
        await writeDoc('gradePoints', { ...state!.gradePoints, [itemType]: list });
    },
    deleteGrade: async ({ itemType, gradeId }) => {
        const list = state!.gradePoints[itemType].filter(g => g.id !== gradeId);
        await writeDoc('gradePoints', { ...state!.gradePoints, [itemType]: list });
    },
    addCodeLetter: async (p) => writeDoc('codeLetters', [...state!.codeLetters, { ...p, id: `c_${Date.now()}` }]),
    addMultipleCodeLetters: async (p) => writeDoc('codeLetters', [...state!.codeLetters, ...p]),
    updateCodeLetter: async (p) => writeDoc('codeLetters', state!.codeLetters.map(c => c.id === p.id ? p : c)),
    reorderCodeLetters: (p) => writeDoc('codeLetters', p),
    deleteCodeLetter: async (id) => writeDoc('codeLetters', state!.codeLetters.filter(c => c.id !== id)),
    addJudge: async (p) => writeDoc('judges', [...state!.judges, { ...p, id: `j_${Date.now()}` }]),
    updateJudge: async (p) => writeDoc('judges', state!.judges.map(j => j.id === p.id ? p : j)),
    reorderJudges: (p) => writeDoc('judges', p),
    deleteMultipleJudges: async (ids) => writeDoc('judges', state!.judges.filter(j => !ids.includes(j.id))),
    updateItemJudges: async (p) => {
        const assignments = state!.judgeAssignments.filter(a => a.itemId !== p.itemId);
        assignments.push({ ...p, id: `${p.itemId}-${p.categoryId}` });
        await writeDoc('judgeAssignments', assignments);
    },
    setJudgeAssignments: (p) => writeDoc('judgeAssignments', p),
    addParticipant: partOps.add, addMultipleParticipants: async (p) => writeDoc('participants', [...state!.participants, ...p]),
    updateParticipant: partOps.update, updateMultipleParticipants: async (p) => {
        const map = new Map(p.map(x => [x.id, x]));
        const next = state!.participants.map(x => map.has(x.id) ? map.get(x.id)! : x);
        await writeDoc('participants', next);
    },
    deleteMultipleParticipants: partOps.deleteMultiple,
    setSchedule: (p) => writeDoc('schedule', p),
    addScheduleEvent: async (p) => writeDoc('schedule', [...state!.schedule, p]),
    updateTabulationEntry: async (p) => {
        const next = state!.tabulation.filter(t => t.id !== p.id);
        next.push(p);
        await writeDoc('tabulation', next);
    },
    updateMultipleTabulationEntries: async (p) => {
        const map = new Map(p.map(x => [x.id, x]));
        const next = state!.tabulation.map(x => map.has(x.id) ? map.get(x.id)! : x);
        p.forEach(x => { if(!state!.tabulation.find(t=>t.id===x.id)) next.push(x); });
        await writeDoc('tabulation', next);
    },
    deleteEventTabulation: async (itemId) => writeDoc('tabulation', state!.tabulation.filter(t => t.itemId !== itemId)),
    saveResult: async (payload: Result) => {
        setState(prev => {
            if (!prev) return prev;
            const nextResults = prev.results.filter(r => r.itemId !== payload.itemId);
            nextResults.push(payload);
            writeDoc('results', nextResults); // Sideways fire
            return { ...prev, results: nextResults };
        });
    },
    addUser: async (p) => writeDoc('users', [...state!.users, { ...p, id: `u_${Date.now()}` }]),
    updateUser: async (p) => writeDoc('users', state!.users.map(u => u.id === p.id ? p : u)),
    deleteUser: async (id) => writeDoc('users', state!.users.filter(u => u.id !== id)),
    updatePermissions: async ({ role, pages }) => writeDoc('permissions', { ...state?.permissions, [role]: pages }),
    updateInstruction: async ({ page, text }) => writeDoc('settings', { ...state?.settings, instructions: { ...state?.settings.instructions, [page]: text } }),
    hasPermission: (tab) => state?.permissions[currentUser!.role].includes(tab) || false,
    backupData: () => {
        const blob = new Blob([JSON.stringify(state)], {type: 'application/json'});
        const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download='artfest.json'; a.click();
    },
    restoreData: async (file) => {
        const reader = new FileReader();
        reader.onload = async (e) => {
            const data = JSON.parse(e.target?.result as string);
            for (const key of Object.keys(data)) {
                await writeDoc(key, data[key]);
            }
        };
        reader.readAsText(file);
    }
  };

  if (error) {
    return (
        <div className="flex items-center justify-center min-h-screen bg-red-50 dark:bg-zinc-900 p-4">
            <div className="text-center text-red-700 dark:text-red-200">
                <h2 className="text-2xl font-bold mb-2">Sync Connection Error</h2>
                <p className="mb-4">{error}</p>
                <button onClick={() => window.location.reload()} className="px-6 py-2 bg-red-600 text-white rounded-xl">Retry</button>
            </div>
        </div>
    );
  }

  return <FirebaseContext.Provider value={contextValue}>{children}</FirebaseContext.Provider>;
};